/**
 * Do not edit directly
 * Generated on Tue, 07 Jun 2022 01:24:43 GMT
 */

export const LightTextPrimary: string;
export const LightTextSecondary: string;
export const LightTextDisabled: string;
export const LightTextPrimaryShades4p: string;
export const LightTextPrimaryShades12p: string;
export const LightTextPrimaryShades30p: string;
export const LightTextSecondaryShades4p: string;
export const LightTextSecondaryShades18p: string;
export const LightPrimaryMain: string;
export const LightPrimaryDark: string;
export const LightPrimaryLight: string;
export const LightPrimaryContrast: string;
export const LightPrimaryShades4p: string;
export const LightPrimaryShades8p: string;
export const LightPrimaryShades12p: string;
export const LightPrimaryShades30p: string;
export const LightPrimaryShades50p: string;
export const LightSecondaryMain: string;
export const LightSecondaryDark: string;
export const LightSecondaryLight: string;
export const LightSecondaryContrast: string;
export const LightSecondaryShades4p: string;
export const LightSecondaryShades8p: string;
export const LightSecondaryShades12p: string;
export const LightSecondaryShades30p: string;
export const LightSecondaryShades50p: string;
export const LightActionActive54p: string;
export const LightActionHover4p: string;
export const LightActionSelected8p: string;
export const LightActionDisabled26p: string;
export const LightActionDisabledBackground12p: string;
export const LightActionFocus12p: string;
export const LightActionShades30p: string;
export const LightErrorMain: string;
export const LightErrorDark: string;
export const LightErrorLight: string;
export const LightErrorContrast: string;
export const LightErrorShades4p: string;
export const LightErrorShades12p: string;
export const LightErrorShades30p: string;
export const LightErrorShades50p: string;
export const LightWarningMain: string;
export const LightWarningDark: string;
export const LightWarningLight: string;
export const LightWarningContrast: string;
export const LightWarningShades4p: string;
export const LightWarningShades12p: string;
export const LightWarningShades30p: string;
export const LightWarningShades50p: string;
export const LightInfoMain: string;
export const LightInfoDark: string;
export const LightInfoLight: string;
export const LightInfoContrast: string;
export const LightInfoShades4p: string;
export const LightInfoShades12p: string;
export const LightInfoShades30p: string;
export const LightInfoShades50p: string;
export const LightSuccessMain: string;
export const LightSuccessDark: string;
export const LightSuccessContrast: string;
export const LightSuccessLight: string;
export const LightSuccessShades4p: string;
export const LightSuccessShades12p: string;
export const LightSuccessShades30p: string;
export const LightSuccessShades50p: string;
export const LightBackgroundPaper: string;
export const LightBackgroundDefault: string;
export const LightOtherDivider: string;
export const LightOtherOutlinedBorder23p: string;
export const LightOtherBackdropOverlay: string;
export const LightOtherFilledInputBackground: string;
export const LightOtherStandardInputLine: string;
export const LightOtherSnackbar: string;
export const LightOtherRatingActive: string;
export const DarkTextPrimary: string;
export const DarkTextSecondary: string;
export const DarkTextDisabled: string;
export const DarkTextPrimaryShades4p: string;
export const DarkTextPrimaryShades12p: string;
export const DarkTextPrimaryShades30p: string;
export const DarkTextSecondaryShades4p: string;
export const DarkTextSecondaryShades18p: string;
export const DarkPrimaryMain: string;
export const DarkPrimaryDark: string;
export const DarkPrimaryLight: string;
export const DarkPrimaryContrast: string;
export const DarkPrimaryShades8p: string;
export const DarkPrimaryShades16p: string;
export const DarkPrimaryShades12p: string;
export const DarkPrimaryShades30p: string;
export const DarkPrimaryShades50p: string;
export const DarkSecondaryMain: string;
export const DarkSecondaryDark: string;
export const DarkSecondaryLight: string;
export const DarkSecondaryContrast: string;
export const DarkSecondaryShades8p: string;
export const DarkSecondaryShades16p: string;
export const DarkSecondaryShades12p: string;
export const DarkSecondaryShades30p: string;
export const DarkSecondaryShades50p: string;
export const DarkActionActive56p: string;
export const DarkActionHover8p: string;
export const DarkActionSelected16p: string;
export const DarkActionDisabled30p: string;
export const DarkActionDisabledBackground12p: string;
export const DarkActionFocus12p: string;
export const DarkActionShades30p: string;
export const DarkErrorMain: string;
export const DarkErrorDark: string;
export const DarkErrorLight: string;
export const DarkErrorContrast: string;
export const DarkErrorShades8p: string;
export const DarkErrorShades12p: string;
export const DarkErrorShades30p: string;
export const DarkErrorShades50p: string;
export const DarkWarningMain: string;
export const DarkWarningDark: string;
export const DarkWarningLight: string;
export const DarkWarningContrast: string;
export const DarkWarningShades8p: string;
export const DarkWarningShades12p: string;
export const DarkWarningShades30p: string;
export const DarkWarningShades50p: string;
export const DarkInfoMain: string;
export const DarkInfoDark: string;
export const DarkInfoLight: string;
export const DarkInfoContrast: string;
export const DarkInfoShades8p: string;
export const DarkInfoShades12p: string;
export const DarkInfoShades30p: string;
export const DarkInfoShades50p: string;
export const DarkSuccessMain: string;
export const DarkSuccessDark: string;
export const DarkSuccessLight: string;
export const DarkSuccessContrast: string;
export const DarkSuccessShades8p: string;
export const DarkSuccessShades12p: string;
export const DarkSuccessShades30p: string;
export const DarkSuccessShades50p: string;
export const DarkBackgroundDefault: string;
export const DarkBackgroundPaperElevation0: string;
export const DarkOtherDivider: string;
export const DarkOtherOutlinedBorder23p: string;
export const DarkOtherFilledInputBackground: string;
export const DarkOtherStandardInputLine: string;
export const DarkOtherSnackbar: string;
export const DarkOtherRatingActive: string;
export const CommonBlack100p: string;
export const CommonWhite30p: string;
export const CommonWhite100p: string;
export const Grey50: string;
export const Grey100: string;
export const Grey200: string;
export const Grey300: string;
export const Grey400: string;
export const Grey500: string;
export const Grey600: string;
export const Grey700: string;
export const Grey800: string;
export const Grey900: string;
export const GreyA100: string;
export const GreyA200: string;
export const GreyA400: string;
export const GreyA700: string;
export const Indigo50: string;
export const Indigo100: string;
export const Indigo200: string;
export const Indigo300: string;
export const Indigo400: string;
export const Indigo500: string;
export const Indigo600: string;
export const Indigo700: string;
export const Indigo800: string;
export const Indigo900: string;
export const IndigoA100: string;
export const IndigoA200: string;
export const IndigoA400: string;
export const IndigoA700: string;
export const DeepPurple50: string;
export const DeepPurple100: string;
export const DeepPurple200: string;
export const DeepPurple300: string;
export const DeepPurple400: string;
export const DeepPurple500: string;
export const DeepPurple600: string;
export const DeepPurple700: string;
export const DeepPurple800: string;
export const DeepPurple900: string;
export const DeepPurpleA100: string;
export const DeepPurpleA200: string;
export const DeepPurpleA400: string;
export const DeepPurpleA700: string;
export const Amber50: string;
export const Amber300: string;
export const Amber400: string;
export const Amber500: string;
export const Amber600: string;
export const Amber700: string;
export const Amber800: string;
export const Amber900: string;
export const AmberA100: string;
export const AmberA200: string;
export const AmberA400: string;
export const AmberA700: string;
export const Orange50: string;
export const Orange100: string;
export const Orange200: string;
export const Orange300: string;
export const Orange400: string;
export const Orange500: string;
export const Orange600: string;
export const Orange700: string;
export const Orange800: string;
export const Orange900: string;
export const OrangeA100: string;
export const OrangeA200: string;
export const OrangeA400: string;
export const OrangeA700: string;
export const Pink50: string;
export const Pink100: string;
export const Pink200: string;
export const Pink300: string;
export const Pink400: string;
export const Pink500: string;
export const Pink600: string;
export const Pink700: string;
export const Pink800: string;
export const Pink900: string;
export const PinkA100: string;
export const PinkA200: string;
export const PinkA400: string;
export const PinkA700: string;
export const DeepOrange50: string;
export const DeepOrange100: string;
export const DeepOrange200: string;
export const DeepOrange300: string;
export const DeepOrange400: string;
export const DeepOrange500: string;
export const DeepOrange600: string;
export const DeepOrange700: string;
export const DeepOrange800: string;
export const DeepOrange900: string;
export const DeepOrangeA100: string;
export const DeepOrangeA200: string;
export const DeepOrangeA400: string;
export const DeepOrangeA700: string;
export const Green50: string;
export const Green100: string;
export const Green200: string;
export const Green300: string;
export const Green400: string;
export const Green500: string;
export const Green600: string;
export const Green700: string;
export const Green800: string;
export const Green900: string;
export const GreenA100: string;
export const GreenA200: string;
export const GreenA400: string;
export const GreenA700: string;
export const Red50: string;
export const Red100: string;
export const Red200: string;
export const Red400: string;
export const Red500: string;
export const Red600: string;
export const Red700: string;
export const Red800: string;
export const Red900: string;
export const RedA100: string;
export const RedA200: string;
export const RedA400: string;
export const RedA700: string;
export const LightGreen50: string;
export const LightGreen100: string;
export const LightGreen200: string;
export const LightGreen300: string;
export const LightGreen400: string;
export const LightGreen500: string;
export const LightGreen600: string;
export const LightGreen700: string;
export const LightGreen800: string;
export const LightGreen900: string;
export const LightGreenA100: string;
export const LightGreenA200: string;
export const LightGreenA400: string;
export const LightGreenA700: string;
export const Purple50: string;
export const Purple100: string;
export const Purple200: string;
export const Purple300: string;
export const Purple400: string;
export const Purple500: string;
export const Purple600: string;
export const Purple700: string;
export const Purple800: string;
export const Purple900: string;
export const PurpleA100: string;
export const PurpleA200: string;
export const PurpleA400: string;
export const PurpleA700: string;
export const Lime50: string;
export const Lime100: string;
export const Lime200: string;
export const Lime300: string;
export const Lime400: string;
export const Lime500: string;
export const Lime600: string;
export const Lime700: string;
export const Lime800: string;
export const Lime900: string;
export const LimeA100: string;
export const LimeA200: string;
export const LimeA400: string;
export const LimeA700: string;
export const LightBlue50: string;
export const LightBlue100: string;
export const LightBlue200: string;
export const LightBlue300: string;
export const LightBlue400: string;
export const LightBlue500: string;
export const LightBlue600: string;
export const LightBlue700: string;
export const LightBlue800: string;
export const LightBlue900: string;
export const LightBlueA100: string;
export const LightBlueA200: string;
export const LightBlueA400: string;
export const LightBlueA700: string;
export const Yellow50: string;
export const Yellow100: string;
export const Yellow200: string;
export const Yellow300: string;
export const Yellow400: string;
export const Yellow500: string;
export const Yellow600: string;
export const Yellow700: string;
export const Yellow800: string;
export const Yellow900: string;
export const YellowA100: string;
export const YellowA200: string;
export const YellowA400: string;
export const YellowA700: string;
export const Cyan50: string;
export const Cyan100: string;
export const Cyan200: string;
export const Cyan300: string;
export const Cyan400: string;
export const Cyan500: string;
export const Cyan600: string;
export const Cyan700: string;
export const Cyan800: string;
export const Cyan900: string;
export const CyanA100: string;
export const CyanA200: string;
export const CyanA400: string;
export const CyanA700: string;
export const Teal50: string;
export const Teal100: string;
export const Teal200: string;
export const Teal300: string;
export const Teal400: string;
export const Teal500: string;
export const Teal600: string;
export const Teal700: string;
export const Teal800: string;
export const Teal900: string;
export const TealA100: string;
export const TealA200: string;
export const TealA400: string;
export const TealA700: string;
export const Blue50: string;
export const Blue100: string;
export const Blue200: string;
export const Blue400: string;
export const Blue500: string;
export const Blue600: string;
export const Blue700: string;
export const Blue800: string;
export const Blue900: string;
export const BlueA100: string;
export const BlueA200: string;
export const BlueA400: string;
export const BlueA700: string;
export const BlueGray50: string;
export const BlueGray100: string;
export const BlueGray200: string;
export const BlueGray300: string;
export const BlueGray400: string;
export const BlueGray500: string;
export const BlueGray600: string;
export const BlueGray700: string;
export const BlueGray800: string;
export const BlueGray900: string;
export const Elevation1: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
}[];
export const Elevation2: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
}[];
export const Elevation3: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
}[];
export const Elevation4: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
}[];
export const Elevation5: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
}[];
export const Elevation6: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
}[];
export const Elevation7: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
}[];
export const Elevation8: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
}[];
export const Elevation9: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
}[];
export const Elevation10: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
}[];
export const Elevation11: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
}[];
export const Elevation12: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
}[];
export const Elevation13: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
}[];
export const Elevation14: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
}[];
export const Elevation15: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
}[];
export const Elevation16: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
}[];
export const Elevation17: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
}[];
export const Elevation18: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
}[];
export const Elevation19: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
}[];
export const Elevation20: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
}[];
export const Elevation21: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
}[];
export const Elevation22: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
}[];
export const Elevation23: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
}[];
export const Elevation24: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
}[];
export const ElevationOutlinedLight: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
};
export const ElevationOutlinedDark: {
  color: string;
  type: string;
  x: number;
  y: number;
  blur: number;
  spread: number;
};
export const FontFamiliesRoboto: string;
export const LineHeights0: string;
export const LineHeights1: string;
export const LineHeights2: string;
export const LineHeights3: string;
export const LineHeights4: string;
export const LineHeights5: string;
export const LineHeights6: string;
export const LineHeights7: string;
export const LineHeights8: string;
export const LineHeights9: string;
export const LineHeights10: string;
export const LineHeights11: string;
export const LineHeights12: string;
export const LineHeights13: string;
export const LineHeights14: string;
export const LineHeights15: string;
export const LineHeights16: string;
export const LineHeights17: string;
export const LineHeights18: string;
export const FontWeightsRoboto0: string;
export const FontWeightsRoboto1: string;
export const FontWeightsRoboto2: string;
export const FontSize0: string;
export const FontSize1: string;
export const FontSize2: string;
export const FontSize3: string;
export const FontSize4: string;
export const FontSize5: string;
export const FontSize6: string;
export const FontSize7: string;
export const FontSize8: string;
export const FontSize9: string;
export const FontSize10: string;
export const FontSize11: string;
export const LetterSpacing0: string;
export const LetterSpacing1: string;
export const LetterSpacing2: string;
export const LetterSpacing3: string;
export const LetterSpacing4: string;
export const LetterSpacing5: string;
export const LetterSpacing6: string;
export const LetterSpacing7: string;
export const LetterSpacing8: string;
export const LetterSpacing9: string;
export const LetterSpacing10: string;
export const LetterSpacing11: string;
export const ParagraphSpacing0: string;
export const TypographyH1: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const TypographyH2: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const TypographyH3: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const TypographyH4: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const TypographyH5: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const TypographyH6: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const TypographyBody1: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const TypographyBody2: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const TypographySubtitle1: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const TypographySubtitle2: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const TypographyOverline: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const TypographyCaption: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const ComponentsAlertTitle: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const ComponentsAvatarInitials: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const ComponentsBadgeLabel: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const ComponentsButtonLarge: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const ComponentsButtonMedium: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const ComponentsButtonSmall: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const ComponentsInputLabel: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const ComponentsHelperText: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const ComponentsInputText: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const ComponentsChip: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const ComponentsTooltip: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const ComponentsTableHeader: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const ComponentsMenuItem: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const ComponentsMenuItemDense: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const ComponentsListSubheader: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const ComponentsBottomNavigationActiveLabel: {
  fontFamily: string;
  fontWeight: string;
  lineHeight: string;
  fontSize: string;
  letterSpacing: string;
  paragraphSpacing: string;
  textCase: string;
  textDecoration: string;
};
export const TextCaseNone: string;
export const TextCaseUppercase: string;
export const TextDecorationNone: string;
